name = "Dimensionless"
uuid = "a24885ee-f44e-4313-a031-cb477fdea68a"
authors = ["Martin Kosch"]
version = "0.1.0"

[compat]
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
